// subscription-app/react/src/pages/Settings.tsx
import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'

const API = 'http://localhost:3001'

export default function Settings() {
  const navigate = useNavigate()
  const [subCount, setSubCount] = useState<number | null>(null)
  const [resetting, setResetting] = useState(false)
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null)

  useEffect(() => {
    fetch(`${API}/api/subscriptions`)
      .then((r) => r.json())
      .then((data) => {
        if (data.success) {
          setSubCount(data.data.length)
        }
      })
      .catch(() => setSubCount(null))
  }, [])

  async function handleReset() {
    setResetting(true)
    setMessage(null)
    try {
      const res = await fetch(`${API}/api/subscriptions`, { method: 'DELETE' })
      const data = await res.json()
      if (!res.ok || !data.success) {
        throw new Error(data.error ?? 'Reset failed')
      }
      setMessage({ type: 'success', text: 'Data reset successfully! Refreshing...' })
      setTimeout(() => navigate('/'), 1000)
    } catch (err: any) {
      setMessage({ type: 'error', text: err.message ?? 'An error occurred' })
      setResetting(false)
    }
  }

  return (
    <div>
      <h1 className="text-2xl font-bold text-gray-900 mb-6">Settings</h1>

      {/* Card 1 — About */}
      <div className="bg-white rounded-[8px] shadow-sm border border-gray-200 p-6 mb-6">
        <h2 className="text-base font-semibold text-gray-900 mb-4">About</h2>
        <dl className="space-y-3 text-sm">
          <div className="flex justify-between">
            <dt className="text-gray-500">App name</dt>
            <dd className="font-medium text-gray-900">SubTrack</dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-gray-500">Description</dt>
            <dd className="font-medium text-gray-900">Phase 5 — Settings & Polish</dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-gray-500">Framework</dt>
            <dd className="font-medium text-gray-900">React 19 + Vite</dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-gray-500">Styling</dt>
            <dd className="font-medium text-gray-900">Tailwind CSS 4</dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-gray-500">Language</dt>
            <dd className="font-medium text-gray-900">TypeScript</dd>
          </div>
        </dl>
      </div>

      {/* Card 2 — Database Info */}
      <div className="bg-white rounded-[8px] shadow-sm border border-gray-200 p-6 mb-6">
        <h2 className="text-base font-semibold text-gray-900 mb-4">Database Info</h2>
        <dl className="space-y-3 text-sm">
          <div className="flex justify-between">
            <dt className="text-gray-500">Backend</dt>
            <dd className="font-medium text-gray-900">SQLite</dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-gray-500">Total subscriptions</dt>
            <dd className="font-medium text-gray-900">
              {subCount === null ? '—' : subCount}
            </dd>
          </div>
        </dl>
      </div>

      {/* Card 3 — Danger Zone */}
      <div className="bg-white rounded-[8px] shadow-sm border border-gray-200 p-6 mb-6">
        <h2 className="text-base font-semibold text-red-600 mb-2">Danger Zone</h2>
        <p className="text-sm text-gray-600 mb-4">
          This will delete all subscriptions and re-seed with default data.
        </p>

        {message && (
          <div
            className={[
              'mb-4 px-4 py-3 rounded-md text-sm font-medium',
              message.type === 'success'
                ? 'bg-green-50 text-green-700 border border-green-200'
                : 'bg-red-50 text-red-700 border border-red-200',
            ].join(' ')}
          >
            {message.text}
          </div>
        )}

        <button
          onClick={handleReset}
          disabled={resetting}
          className="bg-[var(--color-danger)] text-white rounded-md px-4 py-2 text-sm font-medium hover:bg-red-600 transition-colors disabled:opacity-50 cursor-pointer"
        >
          {resetting ? 'Resetting...' : 'Reset Data'}
        </button>
      </div>
    </div>
  )
}

// subscription-app/sveltekit/src/routes/settings/+page.svelte
<script lang="ts">
	let resetting = false;
	let statusMessage: { type: 'success' | 'error'; text: string } | null = null;

	import { onMount } from 'svelte';

	onMount(async () => {
		const res = await fetch('/api/subscriptions');
		if (res.ok) {
			const data = await res.json();
			totalSubs = data.data.length;
		}
	});

	let totalSubs = 0;

	async function resetData() {
		// Clear all subscriptions and re-seed by reloading the app
		resetting = true;
		try {
			// Reset by deleting all records
			for (let i = 0; i < 100; i++) { // safety limit
				const res = await fetch('/api/subscriptions', { method: 'DELETE' });
				const data = await res.json();
				if (!data.success) break;
			}
			statusMessage = { type: 'success', text: 'Data reset successfully! Server will re-seed on next request.' };
		} catch (e) {
			statusMessage = { type: 'error', text: e instanceof Error ? e.message : 'Failed to reset data' };
		} finally {
			resetting = false;
		}
	}
</script>

<div class="max-w-2xl">
	<h1 class="text-2xl font-bold text-foreground mb-6">Settings</h1>

	<div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-6">
		<h2 class="text-lg font-semibold text-foreground mb-4">About</h2>
		<p class="text-sm text-gray-600 mb-2"><strong>Subscription Audit Dashboard</strong></p>
		<p class="text-sm text-gray-500">Phase 1 — Foundation & Scaffold</p>
		<p class="text-xs text-gray-400 mt-4">Built with SvelteKit, Tailwind CSS, Drizzle ORM, and SQLite.</p>
	</div>

	<div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-6">
		<h2 class="text-lg font-semibold text-foreground mb-4">Database Info</h2>
		<div class="flex items-center justify-between py-2">
			<span class="text-sm text-gray-600">Total subscriptions</span>
			<span class="text-sm font-medium text-foreground">{totalSubs}</span>
		</div>
		<div class="flex items-center justify-between py-2 border-t border-gray-100 mt-2 pt-2">
			<span class="text-sm text-gray-600">Database backend</span>
			<span class="text-sm font-medium text-foreground">SQLite</span>
		</div>
	</div>

	{#if statusMessage}
		<div class="mb-6 p-4 rounded-lg" 
			class:bg-green-50={statusMessage.type === 'success'}
			class:bg-red-50={statusMessage.type === 'error'}
			class:border-green-200={statusMessage.type === 'success'}
			class:border-red-200={statusMessage.type === 'error'}
		>
			<p class="text-sm" 
				class:text-green-700={statusMessage.type === 'success'}
				class:text-red-700={statusMessage.type === 'error'}
			>
				{statusMessage.text}
			</p>
		</div>
	{/if}

	<div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
		<h2 class="text-lg font-semibold text-red-600 mb-4">Danger Zone</h2>
		<p class="text-sm text-gray-600 mb-4">This will delete all subscriptions and re-seed with default data.</p>
		<button 
			class="px-4 py-2 bg-danger text-white rounded-md text-sm font-medium hover:bg-red-600 transition-colors disabled:opacity-50"
			onclick={resetData}
			disabled={resetting}
		>
			{resetting ? 'Resetting...' : 'Reset Data'}
		</button>
	</div>
</div>
